/**
 * Claude Code 提示词库的内容源:52 条官方提示词,中英对照。
 * 迁移自本地工具页 claude-prompt-library/index.html(单点迁移,后续更新只改这里);
 * 底稿出处 code.claude.com/docs/zh-CN/prompt-library(2026-09 完整收录)。
 * 字段约定与官方组织一致:阶段 Phase × 类别 Category,另带角色标签、★起点推荐序。
 */

export const PHASES = {
  discover: { zh: "发现", en: "Discover", color: "#5E8C6A" },
  design: { zh: "设计", en: "Design", color: "#7B6BA8" },
  build: { zh: "构建", en: "Build", color: "#C96342" },
  ship: { zh: "交付", en: "Ship", color: "#4E7FA8" },
  operate: { zh: "运营", en: "Operate", color: "#B05A5A" },
} as const;

export const CATS = {
  onboard: { zh: "入职", en: "Onboard" },
  understand: { zh: "理解", en: "Understand" },
  plan: { zh: "计划", en: "Plan" },
  prototype: { zh: "原型", en: "Prototype" },
  implement: { zh: "实现", en: "Implement" },
  test: { zh: "测试", en: "Test" },
  refactor: { zh: "重构", en: "Refactor" },
  review: { zh: "审查", en: "Review" },
  steer: { zh: "引导", en: "Steer" },
  git: { zh: "Git", en: "Git" },
  release: { zh: "发布", en: "Release" },
  debug: { zh: "调试", en: "Debug" },
  incident: { zh: "事件", en: "Incident" },
  data: { zh: "数据", en: "Data" },
  automate: { zh: "自动化", en: "Automate" },
} as const;

export const ROLES = {
  pm: { zh: "产品", en: "PM" },
  design: { zh: "设计", en: "Design" },
  docs: { zh: "文档", en: "Docs" },
  marketing: { zh: "营销", en: "Marketing" },
  security: { zh: "安全", en: "Security" },
  ops: { zh: "运维", en: "Ops" },
  data: { zh: "数据", en: "Data" },
} as const;

export const SRCS = {
  wf: "常见工作流",
  team: "Anthropic 团队博客",
  legal: "法务博客",
  cyber: "安全博客",
  bp: "最佳实践",
  ebook: "扩展代理编码电子书",
} as const;

export const NEEDS = {
  tracker: "需要问题跟踪器(MCP / claude.ai 连接器)",
  gh: "需要已认证的 gh CLI 或 GitHub 连接器",
  browser: "需要可渲染截图的环境(桌面应用 / Chrome 扩展 / Playwright MCP)",
  db: "需要数据仓库或日志存储(MCP / 连接器)",
} as const;

export const PASTES = {
  mockup: "先粘贴 / 拖入 / @ 引用设计稿图片,再发送",
  design: "先粘贴 / 拖入 / @ 引用设计图,再发送",
  screenshot: "先粘贴 / 拖入 / @ 引用控制台截图,再发送",
  plan: "先把 Terraform plan 输出粘贴进提示词,再发送",
  error: "先把报错输出粘贴进提示词,再发送",
  csv: "把文件拖进提示词,或把路径换成你自己的 @ 引用",
} as const;

export type PhaseKey = keyof typeof PHASES;
export type CatKey = keyof typeof CATS;
export type RoleKey = keyof typeof ROLES;
export type NeedKey = keyof typeof NEEDS;
export type PasteKey = keyof typeof PASTES;
export type SrcKey = keyof typeof SRCS;

export interface PromptEntry {
  id: string;
  phase: PhaseKey;
  cat: CatKey;
  /** 「★ 从这里开始」推荐序号(共 5 条),升序即推荐阅读序。 */
  start?: number;
  roles?: RoleKey[];
  paste?: PasteKey;
  needs?: NeedKey;
  /** 英文标题。 */
  te: string;
  /** 中文标题。 */
  tz: string;
  /** 英文提示词模板,{slot} 为可替换槽位。 */
  pe: string;
  /** 中文翻译模板,槽位名与英文一一对应。 */
  pz: string;
  /** 槽位默认填充:{key: [英文示例, 中文示例]}。 */
  s?: Record<string, [string, string]>;
  /** 为什么有效(中文讲解)。 */
  why: string;
  /** 进阶提示(可选)。 */
  next?: string;
  src: SrcKey;
}

export const PROMPTS: PromptEntry[] = [
  {
    id: "get-oriented-in-a",
    phase: "discover",
    cat: "onboard",
    start: 1,
    te: "Get oriented in a new repository",
    tz: "在新代码库中快速上手",
    pe: "give me an overview of this codebase: architecture, key directories, and how the pieces connect",
    pz: "给我概览一下这个代码库:架构、关键目录,以及各部分之间如何衔接",
    why: "描述你想了解什么,而不是指定读哪些文件。Claude 会自己探索项目,返回一份「整体如何拼装」的摘要。",
    next: "运行 /init 生成 CLAUDE.md,让 Claude 每个会话都记住项目背景",
    src: "wf",
  },
  {
    id: "explain-unfamiliar-code",
    phase: "discover",
    cat: "understand",
    te: "Explain unfamiliar code",
    tz: "解释不熟悉的代码",
    pe: "explain what {path} does and how data flows through it. write it up as {format}",
    pz: "解释 {path} 做什么、数据如何流经它,并整理成 {format}",
    s: {
      path: ["src/scheduler/queue.ts", "src/scheduler/queue.ts"],
      format: ["an HTML page with a diagram, then open it in my browser", "一个带图表的 HTML 页面,然后在我的浏览器中打开"],
    },
    why: "指明文件并说明想要的答案格式。HTML 页面可换成图表、要点列表等任何适合你学习方式的格式。",
    next: "设置输出样式(output style),让 Claude 始终按你喜欢的格式解释",
    src: "wf",
  },
  {
    id: "find-where-something-happens",
    phase: "discover",
    cat: "understand",
    start: 2,
    te: "Find where something happens",
    tz: "找到某事发生的位置",
    pe: "where do we {behavior}?",
    pz: "我们在哪里 {behavior}?",
    s: { behavior: ["validate uploaded file types", "校验上传文件的类型"] },
    why: "按行为而非文件名搜索。即使不知道文件叫什么、在哪个目录,也能找到位置。",
    src: "wf",
  },
  {
    id: "see-what-depends-on",
    phase: "discover",
    cat: "understand",
    te: "Check what breaks before you delete",
    tz: "删除前检查会破坏什么",
    pe: "what would break if I deleted {target}?",
    pz: "如果我删掉 {target},哪些地方会坏?",
    s: { target: ["the retryWithBackoff helper", "retryWithBackoff 辅助函数"] },
    why: "删除前先问。调用方和下游影响清单会告诉你:这是一行清理,还是需要协调的跨模块变更。",
    src: "wf",
  },
  {
    id: "trace-how-code-evolved",
    phase: "discover",
    cat: "understand",
    te: "Trace how code evolved",
    tz: "追踪代码的演变",
    pe: "look through the commit history of {path} and summarize how it evolved and why",
    pz: "翻看 {path} 的提交历史,总结它如何演变、为什么",
    s: { path: ["internal/auth/session.go", "internal/auth/session.go"] },
    why: "当问题是「为什么」而不是「是什么」时,指向提交历史。Claude 会读日志和 blame,解释当前实现背后的决策。",
    src: "bp",
  },
  {
    id: "scope-a-change-before",
    phase: "discover",
    cat: "understand",
    roles: ["pm", "design"],
    te: "Scope a change before you start",
    tz: "编码前确定变更范围",
    pe: "which files would I need to touch to {change}?",
    pz: "要 {change},我需要改动哪些文件?",
    s: { change: ["add a dark mode toggle to settings", "给设置页加一个深色模式开关"] },
    why: "排期前先量出工作量。文件清单告诉你这是改一个组件,还是一次跨模块变更。",
    src: "team",
  },
  {
    id: "ask-the-codebase-a",
    phase: "discover",
    cat: "understand",
    roles: ["pm"],
    te: "Ask the codebase a product question",
    tz: "向代码库提产品问题",
    pe: "I am a {role}. walk me through what happens when a user {action}, from the UI down to the result",
    pz: "我是{role}。请带我走一遍用户{action}时发生了什么,从 UI 一路讲到结果",
    s: {
      role: ["PM", "产品经理"],
      action: ["clicks Export to PDF", "点击「导出 PDF」"],
    },
    why: "亮明角色,答案才落在正确的深度。Claude 直接从源码解释产品实际行为,无需你亲自读代码。",
    next: "设置输出样式,让 Claude 始终在这个层级作答",
    src: "team",
  },
  {
    id: "plan-a-multi-file",
    phase: "design",
    cat: "plan",
    roles: ["pm", "design"],
    te: "Plan a multi-file change before touching code",
    tz: "动代码前规划多文件变更",
    pe: "plan how to refactor the {target} to {goal}. list the files you would change, but don't edit anything yet",
    pz: "规划如何重构{target}以{goal}。列出你会改动的文件,但先不要动任何代码",
    s: {
      target: ["payment module", "支付模块"],
      goal: ["support multiple currencies", "支持多币种"],
    },
    why: "一句「先不要编辑」把探索与修改分开,代码变动前先看到方案。想让「先规划」成为默认,按 Shift+Tab 进入计划模式。",
    src: "wf",
  },
  {
    id: "draft-a-spec-by",
    phase: "design",
    cat: "plan",
    roles: ["pm"],
    te: "Draft a spec by interview",
    tz: "通过访谈起草规范",
    pe: "I want to build {feature}. interview me about implementation, UX, edge cases, and tradeoffs until we have covered everything, then write the spec to SPEC.md",
    pz: "我想做{feature}。围绕实现、交互、边界情况和权衡向我提问,问完所有问题后,把需求规格写入 SPEC.md",
    s: { feature: ["per-workspace rate limits", "按工作区的速率限制"] },
    why: "让 Claude 采访你,而不是自己闷头写。它会结构化追问直到需求完整,再落成文档。",
    next: "把采访问题存成 /spec 技能,每个规格都同样开场",
    src: "bp",
  },
  {
    id: "turn-a-meeting-into",
    phase: "design",
    cat: "plan",
    roles: ["pm"],
    needs: "tracker",
    te: "Turn a meeting into tickets",
    tz: "将会议转为工单",
    pe: "read {input} and write up the action items, then create a {tracker} ticket for each with acceptance criteria",
    pz: "读取{input},整理出行动项,然后在{tracker}里为每项创建带验收标准的工单",
    s: {
      input: ["@meeting-notes.md", "@meeting-notes.md"],
      tracker: ["Linear", "Linear"],
    },
    why: "跳过整理纪要这一步。Claude 从非结构化输入提取行动项,经 MCP 直接写进跟踪器——你审的是工单,不是文稿。",
    next: "存为 /tickets 技能",
    src: "team",
  },
  {
    id: "map-edge-cases-before",
    phase: "design",
    cat: "plan",
    roles: ["design", "pm"],
    te: "Map edge cases before building",
    tz: "构建前映射边界情况",
    pe: "list the error states, empty states, and edge cases for {feature} that the design needs to cover",
    pz: "列出{feature}的设计需要覆盖的错误态、空态和边界情况",
    s: { feature: ["the file upload flow", "文件上传流程"] },
    why: "问「缺什么」而不是「有什么」。Claude 会列出快乐路径设计最容易漏掉的错误态、空态与边界。",
    src: "team",
  },
  {
    id: "turn-a-mockup-into",
    phase: "design",
    cat: "prototype",
    roles: ["design", "pm", "marketing"],
    paste: "mockup",
    te: "Turn a mockup into a working prototype",
    tz: "将设计稿变为可运行原型",
    pe: "here is a mockup. build a working prototype I can click through, matching the layout and states shown",
    pz: "这是一张设计稿。做一个我能点击操作的可运行原型,还原图中展示的布局和状态",
    why: "可点击的原型能回答静态稿回答不了的问题。交给工程的是可运行代码,而不是文档里的交互描述。",
    src: "team",
  },
  {
    id: "implement-from-a-screenshot",
    phase: "design",
    cat: "prototype",
    roles: ["design"],
    paste: "design",
    needs: "browser",
    te: "Implement from a screenshot and self-check",
    tz: "从截图实现并自检",
    pe: "implement this design, then take a screenshot of the result, compare it to the original, and fix any differences",
    pz: "实现这个设计,然后给结果截图,与原图对比,修复所有差异",
    why: "给 Claude 一个自检闭环:渲染、与原图比对、迭代,无需你逐个指出差距。",
    next: "用 /goal 让 Claude 持续迭代直到截图一致",
    src: "bp",
  },
  {
    id: "follow-an-existing-pattern",
    phase: "build",
    cat: "implement",
    te: "Follow an existing pattern",
    tz: "遵循现有模式",
    pe: "look at how {example} is implemented to understand the pattern, then build {new} the same way",
    pz: "先看{example}是怎么实现的,理解这个模式,然后照同样的方式实现{new}",
    s: {
      example: ["the GitHub webhook handler", "GitHub webhook 处理器"],
      new: ["a Stripe webhook handler", "一个 Stripe webhook 处理器"],
    },
    why: "指向你已经认可的代码。没有参照时 Claude 用通用最佳实践;有了参照,它遵循你代码库的真实约定。",
    next: "让 Claude 把这些模式写进 CLAUDE.md,以后无需再给参照",
    src: "bp",
  },
  {
    id: "generate-docs-for-code",
    phase: "build",
    cat: "implement",
    roles: ["docs"],
    te: "Generate docs for undocumented code",
    tz: "为未文档化的代码生成文档",
    pe: "find {scope} without {format} comments and add them, matching the style already used in the file",
    pz: "找出{scope}中没有{format}注释的部分并补上,风格与文件中已有注释保持一致",
    s: {
      scope: ["the public functions in src/auth/", "src/auth/ 里的公共函数"],
      format: ["JSDoc", "JSDoc"],
    },
    why: "说清范围和格式。Claude 找出缺失部分并模仿文件已有注释风格,新文档读起来和原有的一致。",
    src: "wf",
  },
  {
    id: "add-a-small-well",
    phase: "build",
    cat: "implement",
    te: "Add a small, well-defined feature",
    tz: "添加小型、定义明确的功能",
    pe: "add a {endpoint} endpoint that returns {payload}",
    pz: "添加一个{endpoint}端点,返回{payload}",
    s: {
      endpoint: ["/health", "/health"],
      payload: ["the app version and uptime", "应用版本和运行时长"],
    },
    why: "说明输入和输出,而不是怎么实现。Claude 会找到相似代码的位置,把新代码加在旁边。",
    src: "wf",
  },
  {
    id: "build-a-small-internal",
    phase: "build",
    cat: "implement",
    roles: ["pm", "design", "marketing", "docs"],
    te: "Build a small internal tool from scratch",
    tz: "从零构建小型内部工具",
    pe: "create a {tool} using HTML, CSS, and vanilla JavaScript, then open it in my browser",
    pz: "用 HTML、CSS 和原生 JavaScript 做一个{tool},然后在我的浏览器里打开",
    s: { tool: ["drag-and-drop Kanban board with three columns", "支持拖拽的三列看板"] },
    why: "不需要项目、框架和构建步骤。描述工具并要求打开,立刻看到它能跑。",
    src: "team",
  },
  {
    id: "work-an-issue-end",
    phase: "build",
    cat: "implement",
    needs: "gh",
    te: "Work an issue end to end",
    tz: "端到端处理 issue",
    pe: "read issue #{issue}, implement the fix, and run the tests",
    pz: "读取 issue #{issue},实现修复,并运行测试",
    s: { issue: ["312", "312"] },
    why: "给编号而不是摘要。Claude 自己读完整工单,你漏提的需求也在里面;改完先验证再报告。",
    src: "wf",
  },
  {
    id: "find-and-update-copy",
    phase: "build",
    cat: "implement",
    roles: ["design", "docs", "marketing"],
    te: "Find and update copy across the codebase",
    tz: "全代码库查找并更新文案",
    pe: 'find every place we say "{copy}" or a close variant, show me each one in context, then update them all to "{new}". leave tests and the changelog alone',
    pz: '找出所有写着「{copy}」或相近说法的地方,逐一带上下文给我看,然后全部改成「{new}」。测试和变更日志不要动',
    s: {
      copy: ["Sign up free", "免费注册"],
      new: ["Start free trial", "开始免费试用"],
    },
    why: "要求匹配「相近变体」并说明跳过什么。字面搜索会漏掉的措辞都能找到,测试夹具和历史记录原样保留。",
    src: "team",
  },
  {
    id: "draft-from-past-examples",
    phase: "build",
    cat: "implement",
    roles: ["docs", "marketing", "pm"],
    te: "Draft a document from past examples",
    tz: "参考过往示例起草",
    pe: "read the {examples} in {folder} to learn the structure and voice, then draft a new one for {topic}",
    pz: "阅读{folder}里的{examples},学习结构和语气,然后为{topic}起草一份新的",
    s: {
      examples: ["privacy impact assessments", "隐私影响评估"],
      folder: ["legal/pia/", "legal/pia/"],
      topic: ["the new analytics integration", "新的分析集成"],
    },
    why: "指向成稿文件夹,而不是描述你的风格。Claude 从你已发布的内容学结构和口吻,第一稿就像你写的。",
    next: "把这种文风保存为技能,每份草稿都从这里起步",
    src: "legal",
  },
  {
    id: "write-tests-run-them",
    phase: "build",
    cat: "test",
    start: 4,
    te: "Write tests, run them, fix failures",
    tz: "编写测试、运行并修复失败",
    pe: "write tests for {path}, run them, and fix any failures",
    pz: "为{path}编写测试,运行它们,并修复所有失败",
    s: { path: ["app/parsers/feed.py", "app/parsers/feed.py"] },
    why: "写、跑、修一口气说完,Claude 会闭环迭代,不会中途停下来等指示。",
    next: "运行 /init 让 Claude 自动学会你的测试命令",
    src: "wf",
  },
  {
    id: "drive-implementation-from-tests",
    phase: "build",
    cat: "test",
    te: "Drive implementation from tests",
    tz: "测试驱动实现",
    pe: "write tests for {feature} first, then implement it until they pass",
    pz: "先为{feature}写测试,再实现功能,直到测试全部通过",
    s: { feature: ["the password reset flow", "密码重置流程"] },
    why: "测试驱动的标准姿势:测试定义「何时算完成」,Claude 迭代实现直到通过。",
    src: "ebook",
  },
  {
    id: "fill-gaps-from-a",
    phase: "build",
    cat: "test",
    te: "Fill gaps from a coverage report",
    tz: "根据覆盖率报告填补空白",
    pe: "read {report} and add tests for the lowest-covered files until each is above {target}%",
    pz: "读取{report},给覆盖率最低的文件补测试,直到每个都高于{target}%",
    s: {
      report: ["coverage/coverage-summary.json", "coverage/coverage-summary.json"],
      target: ["80", "80"],
    },
    why: "指向覆盖率报告而不是靠猜。Claude 读真实数字,把测试写到最需要的地方。",
    next: "设成 /goal,让 Claude 持续补测试直到达标",
    src: "wf",
  },
  {
    id: "migrate-a-pattern-across",
    phase: "build",
    cat: "refactor",
    te: "Migrate a pattern across the codebase",
    tz: "跨代码库迁移模式",
    pe: "migrate everything from {from} to {to}: identify every place that needs to change, then make the changes",
    pz: "把所有代码从{from}迁移到{to}:先找出每一处需要修改的地方,再动手改",
    s: {
      from: ["the old logging API", "旧日志 API"],
      to: ["the structured logger", "结构化 logger"],
    },
    why: "说清旧模式和新模式,并要求先列出全部调用点——你能核对没有遗漏。跨大量文件时可用 /batch,由后台子代理分批修改并各开一个 PR。",
    src: "wf",
  },
  {
    id: "port-code-between-languages",
    phase: "build",
    cat: "refactor",
    te: "Port code to another language",
    tz: "跨语言移植代码",
    pe: "port {source} to {target}, keeping the same {keep}",
    pz: "把{source}移植到{target},保持{keep}不变",
    s: {
      source: ["this Python module", "这个 Python 模块"],
      target: ["Rust", "Rust"],
      keep: ["public API and test behavior", "公共 API 与测试行为"],
    },
    why: "不只说目标语言,还要说「保持什么不变」。指定必须一致的 API 或行为,移植就有了可校验的契约。",
    src: "team",
  },
  {
    id: "optimize-against-a-measurable",
    phase: "build",
    cat: "refactor",
    roles: ["data"],
    te: "Optimize against a measurable target",
    tz: "面向可测量目标优化",
    pe: "optimize {target} to bring {metric} from {current} down to under {goal}",
    pz: "优化{target},把{metric}从{current}降到{goal}以内",
    s: {
      target: ["the search query", "搜索查询"],
      metric: ["p95 latency", "p95 延迟"],
      current: ["2s", "2 秒"],
      goal: ["500ms", "500 毫秒"],
    },
    why: "给出指标和目标值,「完成」就有了明确定义。",
    next: "设成 /goal,让 Claude 持续测量、迭代直到达标",
    src: "ebook",
  },
  {
    id: "fix-a-precise-visual",
    phase: "build",
    cat: "refactor",
    roles: ["design"],
    te: "Fix a precise visual bug",
    tz: "修复精确的视觉 bug",
    pe: "the {element} extends {amount} beyond the {container} on {viewport}. fix it.",
    pz: "在{viewport}上,{element}超出了{container}{amount}。修掉它。",
    s: {
      element: ["login button", "登录按钮"],
      amount: ["20px", "20px"],
      container: ["card border", "卡片边框"],
      viewport: ["mobile", "移动端"],
    },
    why: "精确的视觉反馈换来精确的修复:说清元素、数值和视口。",
    next: "加预览工具,让 Claude 自己截图验证修复效果",
    src: "ebook",
  },
  {
    id: "review-your-changes-before",
    phase: "build",
    cat: "review",
    start: 5,
    te: "Review your changes before you commit",
    tz: "提交前审查你的变更",
    pe: "review my uncommitted changes and flag anything that looks risky before I commit",
    pz: "审查我未提交的改动,在我提交前标出任何看起来有风险的地方",
    why: "趁问题还便宜时抓住它。Claude 读的是完整改动文件而不只是 diff 行,能发现快速自审漏掉的问题。",
    next: "用 /code-review 一个命令完成同样的检查",
    src: "wf",
  },
  {
    id: "review-a-pull-request",
    phase: "build",
    cat: "review",
    needs: "gh",
    te: "Review a pull request",
    tz: "审查拉取请求",
    pe: "review PR #{pr} and summarize what changed, then list any concerns",
    pz: "审查 PR #{pr},总结改动内容,然后列出所有疑虑",
    s: { pr: ["247", "247"] },
    why: "Claude 在整个代码库的上下文里审查,而不只看 diff——它读改动的代码及其调用处,能抓住纯 diff 审查漏掉的问题。",
    next: "给每个 PR 自动开启代码审查",
    src: "wf",
  },
  {
    id: "review-infrastructure-changes-before",
    phase: "build",
    cat: "review",
    roles: ["security", "ops"],
    paste: "plan",
    te: "Review infrastructure changes before applying",
    tz: "应用前审查基础设施变更",
    pe: "here is my Terraform plan output. what is this going to do, and is anything here going to cause problems?",
    pz: "这是我的 Terraform plan 输出。它将要做什么?其中有什么会引发问题吗?",
    why: "plan 输出密集难读。粘贴进来,得到一份「实际会改什么」的平实摘要,应用之前先看清。",
    src: "team",
  },
  {
    id: "run-a-security-review",
    phase: "build",
    cat: "review",
    roles: ["security"],
    te: "Run a security review with a subagent",
    tz: "使用子代理运行安全审查",
    pe: "use a subagent to review {path} for security issues and report what it finds",
    pz: "用子代理审查{path}的安全问题,并汇报发现",
    s: { path: ["src/api/", "src/api/"] },
    why: "子代理在自己的上下文窗口里跑审计、只回传摘要,长审计不会挤占主会话。内置通用子代理开箱即用。",
    next: "搭一个团队共享的专用安全审查子代理",
    src: "bp",
  },
  {
    id: "review-content-before-sending",
    phase: "build",
    cat: "review",
    roles: ["marketing", "docs"],
    te: "Catch issues before formal review",
    tz: "发送前审查内容",
    pe: "review {file} for {concerns} and list anything I should fix before it goes to {reviewer}",
    pz: "审查{file}是否存在{concerns},列出在提交给{reviewer}前我该修正的所有问题",
    s: {
      file: ["launch-post.md", "launch-post.md"],
      concerns: ["unsupported claims, missing attributions, and brand-guideline issues", "无依据的宣称、缺失的出处和品牌规范问题"],
      reviewer: ["legal", "法务"],
    },
    why: "让人花时间之前先过一遍机器初审。点名要检查的关注点,审查才有针对性。",
    next: "把审查清单沉淀成全团队可复用的技能",
    src: "legal",
  },
  {
    id: "course-correct-a-wrong",
    phase: "build",
    cat: "steer",
    te: "Course-correct a wrong approach",
    tz: "纠正错误的方法",
    pe: "that is not right: {feedback}. try a different approach",
    pz: "这不对:{feedback}。换一种思路重试",
    s: { feedback: ["the function signature needs to stay backward-compatible", "函数签名必须保持向后兼容"] },
    why: "说出 Claude 漏掉的约束,而不只是「错了」。具体的理由给它一个可满足的硬约束,而不是再猜一次。",
    next: "连按两次 Esc 打开回退菜单,恢复代码和对话,从干净状态重试",
    src: "bp",
  },
  {
    id: "narrow-the-scope-of",
    phase: "build",
    cat: "steer",
    te: "Narrow the scope of a change",
    tz: "缩小变更范围",
    pe: "that is too much. keep only the changes to {scope} and undo your other edits",
    pz: "改多了。只保留对{scope}的改动,其余编辑全部撤销",
    s: { scope: ["the validation logic in src/forms/", "src/forms/ 里的校验逻辑"] },
    why: "方向对但改动过宽时,要求「只保留一部分」比全部回退更好。划清边界,小修就不会演变成重构。",
    src: "bp",
  },
  {
    id: "turn-a-correction-into",
    phase: "build",
    cat: "steer",
    te: "Turn a correction into a rule",
    tz: "将纠正转化为规则",
    pe: "you keep {mistake}. add a rule to CLAUDE.md so this stops happening",
    pz: "你总是{mistake}。往 CLAUDE.md 加一条规则,别再犯",
    s: { mistake: ["using default exports when this project uses named exports", "在这个用命名导出的项目里用默认导出"] },
    why: "聊天里的纠正不会同步给团队;写进 CLAUDE.md 的规则提交后人人共享,Claude 每次会话开始都会读。",
    next: "打开 /memory 检查 Claude 写了什么",
    src: "bp",
  },
  {
    id: "resolve-merge-conflicts",
    phase: "ship",
    cat: "git",
    te: "Resolve merge conflicts",
    tz: "解决合并冲突",
    pe: "resolve the merge conflicts in this branch and explain what you kept from each side",
    pz: "解决这个分支的合并冲突,并解释每一侧你各保留了什么",
    why: "说想要的状态,而不是逐个教怎么处理标记。要求给出理由,合并结果可审查,不是黑盒。",
    src: "wf",
  },
  {
    id: "commit-with-a-generated",
    phase: "ship",
    cat: "git",
    te: "Commit with a generated message",
    tz: "用生成的消息提交",
    pe: "commit these changes with a message that summarizes what I did",
    pz: "提交这些改动,提交信息概括我做了什么",
    why: "让 Claude 从 diff 推导提交信息,且贴合仓库现有的提交风格。",
    src: "wf",
  },
  {
    id: "open-a-pull-request",
    phase: "ship",
    cat: "git",
    needs: "tracker",
    te: "Open a pull request from a ticket",
    tz: "从工单打开拉取请求",
    pe: "find the {tracker} ticket about {topic} and open a PR that implements it",
    pz: "找到{tracker}里关于{topic}的工单,开一个实现它的 PR",
    s: {
      tracker: ["Linear", "Linear"],
      topic: ["the login timeout", "登录超时"],
    },
    why: "一个提示词读完需求、完成修改、开好 PR,省掉跟踪器、编辑器和 GitHub 之间的来回切换。",
    src: "wf",
  },
  {
    id: "draft-release-notes-from",
    phase: "ship",
    cat: "release",
    roles: ["pm", "docs", "marketing"],
    te: "Draft release notes from git history",
    tz: "从 git 历史起草发布说明",
    pe: "compare {from} to {to} and draft release notes grouped by feature, fix, and breaking change",
    pz: "对比{from}和{to},按新功能、修复、破坏性变更分组起草发布说明",
    s: {
      from: ["v2.3.0", "v2.3.0"],
      to: ["v2.4.0", "v2.4.0"],
    },
    why: "给两个参照点和想要的结构。Claude 读两点之间的提交日志,起草出你只需微调的变更记录。",
    next: "存为 /changelog 技能",
    src: "wf",
  },
  {
    id: "write-a-ci-workflow",
    phase: "ship",
    cat: "release",
    roles: ["ops"],
    te: "Write a CI workflow",
    tz: "编写 CI 工作流",
    pe: "write a GitHub Actions workflow that {steps} on every push to {branch}",
    pz: "写一个 GitHub Actions 工作流:每次推送到{branch}时{steps}",
    s: {
      steps: ["runs the tests and deploys to staging", "运行测试并部署到预发环境"],
      branch: ["main", "main"],
    },
    why: "说清「何时触发、做什么」,YAML 自动生成并与项目的构建测试命令对齐。",
    src: "wf",
  },
  {
    id: "find-and-fix-a",
    phase: "operate",
    cat: "debug",
    start: 3,
    te: "Find and fix a failing test",
    tz: "找到并修复失败的测试",
    pe: "the {test} test is failing, find out why and fix it",
    pz: "{test} 测试挂了,查明原因并修好它",
    s: { test: ["UserAuth", "UserAuth"] },
    why: "只描述症状,不必知道哪个文件坏了。Claude 跑测试看到失败,追到源头,修好为止。",
    src: "wf",
  },
  {
    id: "investigate-a-reported-error",
    phase: "operate",
    cat: "debug",
    roles: ["ops"],
    te: "Investigate a reported error",
    tz: "调查报告的错误",
    pe: "users are seeing {symptom} on {where}. investigate and tell me what is going on",
    pz: "用户在{where}上遇到{symptom}。排查一下,告诉我怎么回事",
    s: {
      symptom: ["500 errors", "500 错误"],
      where: ["/api/settings", "/api/settings"],
    },
    why: "说症状和位置即可,Claude 读相关代码路径、追踪可能原因。有堆栈或日志就一并粘贴。",
    next: "在运行手册里放深链,预填此提示词直接打开 Claude",
    src: "wf",
  },
  {
    id: "fix-a-build-error",
    phase: "operate",
    cat: "debug",
    roles: ["ops"],
    paste: "error",
    te: "Fix a build error at the root",
    tz: "从根源修复构建错误",
    pe: "here is a build error. fix the root cause and verify the build succeeds",
    pz: "这是一个构建报错。修复根因,并验证构建通过",
    why: "要求「根因 + 验证」,防止表面补丁把错误压住却没修好。",
    src: "bp",
  },
  {
    id: "investigate-a-production-incident",
    phase: "operate",
    cat: "incident",
    roles: ["ops", "security"],
    te: "Investigate a production incident",
    tz: "调查生产事件",
    pe: "{symptom}. check the logs, recent deploys, and config changes, then tell me the most likely cause",
    pz: "{symptom}。检查日志、最近的部署和配置变更,告诉我最可能的原因",
    s: { symptom: ["the checkout endpoint started returning 500s an hour ago", "结账接口一小时前开始返回 500"] },
    why: "列出要交叉核对的证据源,而不是列步骤。Claude 把日志、git 历史、配置放在一起收敛出原因。",
    next: "用 MCP 接入 Sentry 或日志系统",
    src: "wf",
  },
  {
    id: "diagnose-from-a-console",
    phase: "operate",
    cat: "incident",
    roles: ["ops", "data"],
    paste: "screenshot",
    te: "Diagnose from a console screenshot",
    tz: "从控制台截图诊断",
    pe: "here is a screenshot of {console}. walk me through why {resource} is failing and give me the exact commands to fix it",
    pz: "这是一张{console}的截图。带我分析{resource}为什么失败,并给出修复的确切命令",
    s: {
      console: ["the GCP Kubernetes dashboard", "GCP Kubernetes 控制台"],
      resource: ["this pod", "这个 Pod"],
    },
    why: "云控制台只给你看问题,不给修它的命令。Claude 读截图,把仪表盘翻译成可执行的 kubectl/gcloud/aws 命令。",
    src: "team",
  },
  {
    id: "query-logs-in-plain",
    phase: "operate",
    cat: "incident",
    roles: ["security", "ops", "data"],
    needs: "db",
    te: "Query logs in plain English",
    tz: "用白话查询日志",
    pe: "show me all {events} for {scope} over {timeframe}. write the query, run it, and tell me what stands out",
    pz: "查一下{scope}在{timeframe}内的所有{events}。写查询、跑起来,告诉我有什么异常",
    s: {
      events: ["failed logins", "失败登录"],
      scope: ["the auth service", "认证服务"],
      timeframe: ["the past 24 hours", "过去 24 小时"],
    },
    why: "提问代替写 SQL。Claude 生成查询、在接入的日志源上运行,并展示查询和结果,跑了什么一目了然。",
    src: "cyber",
  },
  {
    id: "analyze-a-data-file",
    phase: "operate",
    cat: "data",
    roles: ["data", "pm", "marketing"],
    paste: "csv",
    te: "Analyze a data file",
    tz: "分析数据文件",
    pe: "read {file}, summarize the key patterns, and write the results to {output}",
    pz: "读取{file},总结关键模式,把结果写到{output}",
    s: {
      file: ["@reports/q1-signups.csv", "@reports/q1-signups.csv"],
      output: ["an HTML page with charts, then open it in my browser", "一个带图表的 HTML 页面,然后在我的浏览器中打开"],
    },
    why: "一次性问题不必写一次性脚本。指向项目里的文件,Claude 直接读、找模式、按要求输出。",
    next: "用 MCP 直连数据源,免去导出文件",
    src: "team",
  },
  {
    id: "generate-variations-from-performance",
    phase: "operate",
    cat: "data",
    roles: ["marketing", "data"],
    paste: "csv",
    te: "Generate variations from performance data",
    tz: "根据效果数据生成变体",
    pe: "read {file}, find the underperforming {items}, and generate {n} new variations that stay under {limit} characters",
    pz: "读取{file},找出表现不佳的{items},生成{n}个不超过{limit}字符的新变体",
    s: {
      file: ["@ads-performance.csv", "@ads-performance.csv"],
      items: ["headlines", "广告标题"],
      n: ["20", "20 条"],
      limit: ["90", "90"],
    },
    why: "把约束放在开头,生成结果才不会越界。Claude 读指标、挑出该换的、按字数限制产出替代方案。",
    next: "用 MCP 直连广告平台,免去导出文件",
    src: "team",
  },
  {
    id: "turn-a-recurring-task",
    phase: "operate",
    cat: "automate",
    te: "Turn a recurring task into a skill",
    tz: "将重复任务转变为技能",
    pe: "create a /{name} skill for this project that {steps}",
    pz: "为这个项目创建一个/{name}技能,它会{steps}",
    s: {
      name: ["ship", "ship"],
      steps: ["runs the linter and tests, then drafts a commit message", "跑代码检查和测试,然后起草提交信息"],
    },
    why: "步骤说一次,以后当命令复用。Claude 写出团队成员都能运行的技能。",
    src: "wf",
  },
  {
    id: "add-a-hook-for",
    phase: "operate",
    cat: "automate",
    te: "Add a hook for repeat behavior",
    tz: "为重复行为添加钩子",
    pe: "write a hook that {action} after every {event}",
    pz: "写一个钩子:每次{event}之后自动{action}",
    s: {
      action: ["runs prettier", "运行 prettier"],
      event: ["edit to a .ts or .tsx file", "编辑 .ts/.tsx 文件"],
    },
    why: "钩子把行为变成自动化,不再依赖你记得去要求。说清触发器和动作,Claude 生成钩子配置。",
    src: "bp",
  },
  {
    id: "connect-a-tool-with",
    phase: "operate",
    cat: "automate",
    te: "Connect a tool with MCP",
    tz: "使用 MCP 连接工具",
    pe: "set up the {server} MCP server so you can read my {data} directly",
    pz: "配置{server}的 MCP 服务器,让你能直接读我的{data}",
    s: {
      server: ["Sentry", "Sentry"],
      data: ["error reports", "错误报告"],
    },
    why: "数据源接一次,胜过每次会话贴数据。MCP 配好后,Claude 询问时直接从工具读取。",
    src: "wf",
  },
  {
    id: "capture-what-to-remember",
    phase: "operate",
    cat: "automate",
    roles: ["pm", "docs"],
    te: "Capture what to remember for next time",
    tz: "记录下次要记住的内容",
    pe: "summarize what we did this session and suggest what to add to CLAUDE.md",
    pz: "总结这次会话我们做了什么,并建议往 CLAUDE.md 里补充什么",
    why: "趁还没忘就问。Claude 知道这次会话弄明白了什么,提议写进 CLAUDE.md 的条目,让下次会话带着上下文开场。",
    src: "team",
  },
];

/** 用槽位默认值渲染模板(lang 取 "en" | "zh")。 */
export function fillPrompt(p: PromptEntry, lang: "en" | "zh"): string {
  const tpl = lang === "en" ? p.pe : p.pz;
  return tpl.replace(/\{(\w+)\}/g, (_, k: string) => (p.s && p.s[k] ? p.s[k][lang === "en" ? 0 : 1] : k));
}

/** 搜索索引:标题、模板、填充结果、阶段/类别/角色词全部拼进一段小写文本。 */
export function promptIndex(p: PromptEntry): string {
  return [
    p.tz,
    p.te,
    p.pe,
    p.pz,
    fillPrompt(p, "en"),
    fillPrompt(p, "zh"),
    PHASES[p.phase].zh,
    PHASES[p.phase].en,
    CATS[p.cat].zh,
    CATS[p.cat].en,
    p.cat,
    ...(p.roles ?? []).map((r) => `${ROLES[r].zh} ${ROLES[r].en} ${r}`),
    p.why,
  ]
    .join(" ")
    .toLowerCase();
}
